# Generated by Django 3.2.2 on 2021-05-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210514_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag_lunch',
            field=models.BooleanField(default=True, verbose_name='Обед'),
        ),
    ]
