# Generated by Django 3.2.2 on 2021-05-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_rename_name_ingredient_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='dimension',
        ),
    ]
